### ISSUE TITLE
Chaining 2 ffmpeg operation times out

### ISSUE THREAD

**Issue by Herz3h** [bramp/ffmpeg-cli-wrapper#143]
Hello,

When i chain two trim operations (split files in 2 parts), the second operation throws exception that it timed out. I'm running this on Android, i checked the sources, and it seems there is a hardcoded timeout of 1second... As if this library is expecting every operation to be done under 1second ?

The two operations are running sequentially. But it seems the process is not destroyed yet even tho p.destroy() is called. 

Any workaround ?

**Comment by bramp** [comment]
Are you referring to the 1 second timeout in [throwOnError](https://github.com/bramp/ffmpeg-cli-wrapper/blob/bdaac390352716e074b513566fca2f63661e7b5d/src/main/java/net/bramp/ffmpeg/FFcommon.java#L46)?  That timeout is after the ffmpeg process has closed stdout, and we wait 1 second for the process to return a exit code. Typically that should happen instantly, the 1 second is just a precaution.

Jobs that take more than 1 second, work perfectly well, and in fact there are a few of them in the unit/integration tests.

So I'm unsure exactly what this issue is, but the fact you say the process isn't destroyed, makes me suspect something odd with Android is happening.

Could you provide a simple example that fails?

**Comment by Herz3h** [comment]
Actually i used this project on Android with RxJava, and i wrapper the createJob(..).run() into Single type in RxJava. And whenever an IOException was triggerd by this library, RxJava would thorw UndeliverableException and stop all the process of ffmpeg. So i disabled this UndeliverableException handler as explained here : https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#error-handling

It still throws Timed out exception but yet works fine. Now i understand it justs waits for the process to finish. So we can close this, thanks for the clarification i guess this was more RxJava/Android related.
