### ISSUE TITLE
Feature : Provide ready to use FFMPEG JARS

### ISSUE THREAD

**Issue by goxr3plus** [bramp/ffmpeg-cli-wrapper#179]
For example in this project -> https://github.com/a-schild/jave2  you can get the Jave2-core which is basically the wrapper around FFMPEG and based on your system get [another jar which contains the FFMPEG](https://github.com/a-schild/jave2/tree/master/jave-native-win64/src/main/resources/ws/schild/jave/native) .

This is easier than making our own implementation of how to copy the jar to the system then delete it etc ...

Would be a great missing feature for this library .

**Comment by st-h** [comment]
@goxr3plus wouldn't it be possible to just use the jars form jave2 in case you need ffmpeg wrapped inside a jar? In case you are using an OS with a reasonable package manager (like linux) it usually is just a single command to have ffmpeg installed (and updated), but that depends on your actual use case as well. So I can't tell how useful that actually is.

**Comment by goxr3plus** [comment]
Let's say i want to include this library with an application in which the
user will have nothing to type or execute. Linux is for advanced users.
What about Mac OS and Windows. Like the functionality is good but i see a
potential here.

It's just a recommendation and the only reason i used Jave2 instead of this
library because i found extremely difficult to keep it running smoothly for
all 3 platforms without running custom code for copying FFMPEG library.

**Comment by st-h** [comment]
@goxr3plus sorry, that is not what I meant to say. You should probably be able to use the wrapper jars from jave2 together with this library. I haven't tried, but from the links you posted previously it looks like that should work.

**Comment by bramp** [comment]
@st-h that's a good suggestion.

@goxr3plus I'm not going to add jars with the binaries, as the support cost (to me) is way too high. I don't have the mechanism to test ffmpeg on all platforms, and I don't want to be pushing updates every few weeks when new binaries come out.

Additionally, the Jave2 ffmpeg builds don't contain some of the more powerful encoders (such as the ACC), because that is distributed under a licence which forbids shipping binaries. When I originally wrote this library, I was using a statically compiled ffmpeg, instead of the ffmpeg provided by debian, because I needed features that weren't under a permissive licence (and thus binaries weren't available).

**Comment by namannigam** [comment]
@bramp @st-h If I understand the requirement correctly and that the binaries would not be added to jars. Is there any existing example to bundle(zip) the `ffmpeg` binaries with a jar possibly using maven?
