### ISSUE TITLE
Byte[ ] or ByteBuffer input

### ISSUE THREAD

**Issue by Squrrli** [bramp/ffmpeg-cli-wrapper#190]
The ffmpeg-cli-wrapper library is a simple wrapper around the ffmpeg command line. If you have questions on how to use the library, please check out the [usage](https://github.com/bramp/ffmpeg-cli-wrapper#usage), or [random examples](https://github.com/bramp/ffmpeg-cli-wrapper/wiki/Random-Examples). If that doesn't solve your problem please fill out the following:

**The question**
Deom all examples I have see the input is a string (be it referencing a webcam or a filename) however I am trying to stream from an android app to a media server. The format of the incoming stream (from a drone) is received as a Byte[ ] and as such i was wondering how/ if I can use that as an input for this wrapper. I understand it might not work as it is a CLI_wrapper.

I have not tried anything yet as I just don't know how I would reference the array by a string.

**Comment by Euklios** [comment]
Sorry for the late reply.

The first problem you'll have is android.
This library is just a wrapper around the ffmpeg executable.
As far as I know, it's not possible to execute an executable like ffmpeg on an Android device.

Second, what would byte[] as input mean?
If your drone is sending a byte[], it's most likely a still image.
When loaded as a library, it should be quite easy to feed this to ffmpeg, but this might be an entirely different topic for this library.

Forwarding the images using a TCP socket to FFmpeg might make it possible, but you might need something entirely different.
If sending the images via socket would be acceptable, #334 would be concerned about that.

I'll close this issue for now. Feel free to re-open it if you have any more questions or if your problem is not covered by #334.
Feel free to provide an ffmpeg command if you managed to solve this issue in another way so we can try to integrate it into our code/tests.
