### ISSUE TITLE
Set input duration

### ISSUE THREAD

**Issue by zhaakhi** [bramp/ffmpeg-cli-wrapper#94]
FFmpegBuilder has an option for input start offset, but not for input duration ("-t")

**Comment by phuongnd11** [comment]
Can you add support for this feature? I also tried using .addExtraArgs("-t 60") but it didn't work:
Unrecognized option 't 60'.

**Comment by bramp** [comment]
Sure, but in the meantime​ you can do this with: `.addExtraArgs("-t",
"60")`. Notice that you pass each argument separately.

On Apr 7, 2017 1:15 AM, "phuongnd11" <notifications@github.com> wrote:

Can you add support for this feature? I also tried using .addExtraArgs("-t
60") but it didn't work:
Unrecognized option 't 60'.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bramp/ffmpeg-cli-wrapper/issues/94#issuecomment-292472319>,
or mute the thread

**Comment by phuongnd11** [comment]
It works. Thanks.

**Comment by stepan-romankov** [comment]
Hi, @bramp,

I want to notice that it will be an issue to set start offset and duration in case of multiple streams:

> ffmpeg -ss 10 -t 10,00 -i file1.m4 -ss 10 -t 10,00 -i file2.m4  ... 

Would you accept pull request if I refactor how inputs are configured ("ss" and "t" will belong to an input ) keeping backward compatibility?

**Comment by Euklios** [comment]
Closed thanks to #339
